version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_LISTENERS: "PLAINTEXT://192.168.1.84:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.1.84:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

